spring.web.resources.static-locations= classpath:/static/, classpath:/templates/
server.port=8080
chatgpt.apiKey=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
chatgpt.apiHost=https://api.openai.com/
# key,Use your own key
SECRET_KEY=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
connectTimeout=60000
connectionRequestTimeout=60000
socketTimeout=60000
#
#spring.mail.host=smtp.qq.com
#spring.mail.port=587
#spring.mail.username=1364549020@qq.com
#spring.mail.password=gvpweprmkzlgheca
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#
spring.mail.host=smtp.qq.com
spring.mail.port=587
#spring.mail.port=465
spring.mail.username=3170085380@qq.com
spring.mail.password=rxnwknvhrnkqdfdb
spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.socketFactory.class=jetavax.n.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.starttls.enable=true


spring.datasource.url = jdbc:mysql://localhost:3306/dangfangcaifu?characterEncoding=utf-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8

spring.datasource.username = root
spring.datasource.password = 123456
spring.datasource.hikari.maximum-pool-size = 15

wx.appId=wxc595fde6ad629391
wx.appSecret=??AppSecret


# ?spring????bean?id, ????forestConfiguration
forest.bean-id=forestConfiguration
# ??HTTP API? ?????okhttp3????????httpclient
forest.backend=okhttp3
# ?????????????500
forest.max-connections=1000
# ???????????????500
forest.max-route-connections=500
# ????????????, ????3000
forest.timeout=3000
# ????????????, ????2000
forest.connect-timeout=3000
# ?????HTTPS???SSL??????SSLv3
#forest.ssl-protocol=SSLv3
# ???????????true??????????????????@LogEnabled
forest.logEnabled=true

# ie
dongfangcaifu.cookie=qgqp_b_id=dc483e32c2d8b96bdedb5d061884ce60; st_nvi=Q05vtEKnqLTbIbjENZn5La7ea; nid18=0bcd9d7a85d5e7327284b540d8fb8064; nid18_create_time=1776154218768; gviem=At93iLMdLhDE2A0BYhEyxeda4; gviem_create_time=1776154218768; quote_lt=1; emshistory=%5B%22%E5%9B%BD%E9%87%91%E8%AF%81%E5%88%B8%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%22%2C%22%E6%B2%AA%E8%82%A1%E9%80%9A%22%5D; mtp=1; vtpst=|; websitepoptg_api_time=1780904886692; ct=g3pCQTOTflG-iVvBJA0LzD5WH48d9GQfGaW_ZOpmG40JeiZa7iHe2DsmqFzuKhIZoCGMQGpjK-88QoxuMwqkBjcrOe3TCuEDPGK_IFAgFhpEBfEbrULzJ6OLzu3ifyVUhQmISOsKYNdbKgQsiMRxui-epUKqy-V_4mqK_DLtP1g; ut=FobyicMgeV5GkRiUmIIADq03fwkNY1WSvEOW8OyRC-IsogC1uraYT1qgyF8QnHTAs9KWOdsd3XIHEDM7nBwsfeRCXhhVjyrJ-vQVCjCzEY2ObnNZy0nF7Tbrjnrm8wG-0vdq1oIWF_cuEK99gimFxnXq2_WW3SpgyWcDlUZKYBuKEoNYxS9FZ8FniUyiXIgw307sBxlqYMrDjyGDs3hxoU36F7xyhxoYn2UCdTFEWXa5GYIB9stUHhDQ00HsJpYt_quZnad7xMK_LtX1NUsorsl-HzWyLyrGryJ79vO2vZegZOp_5EbIySt25Tqe6PLRVDeWoeXUpvPmhwpZcOPrpyq23KsKiz7KyCwWpKeExH6-TnOEmC2_qjP4eure-d0TdF0LReKZSzZzzOeM93tzO4hv6uGcEGGI9xUJjlhLqecf4wIjxvHVrhr9ixX73MfhPJqEqRYaOTpH3cOaQzwUNe1ydH0GoWtjymg1ItzSKaQpVK2XEm0UmIxK2Led5pBaooi1z9pJrO0; pi=9283027483348500%3Bt9283027483348500%3B%E8%82%A1%E5%8F%8BA50921282v%3B9l%2F7dMKFqI5hIB9aP0QvKztl0u5p7LplnjhzzWqNj6%2BdT8TOxmPCXLyD2MSwivGjcxua5Ns8t7GP64Vi8PpdnpYCAQz08HVrk0nWLC2xpkFaBNME3Fcs7%2FiiZWFRJyA%2F7VLKL9L4RJnN9FeWBaNKeg4%2BQtoav0x%2Bs%2BhvbJW5h0G8%2Ft%2Bg4Irg0KsriWML1%2Bjp6X%2BDwihC%3BxZk26FGdlxgIBtoA97vVzCnJERddVQ3pcN23K4vxuzmkdY7%2FmhOWaFxS%2Fg3fnc7io4TC%2FqnqxjS9oEywU0aM1O9IWRvN%2BviHLJuUVmBmODvOF7OmmfgvnFlVKULoShZ3B2LglMYGwn9oXR%2BxcEynVwYUVmsCNw%3D%3D; uidal=9283027483348500%e8%82%a1%e5%8f%8bA50921282v; sid=; fullscreengg=1; fullscreengg2=1; st_si=23263583404730; st_asi=delete; wsc_checkuser_ok=1; st_pvi=82959104877326; st_sp=2025-03-04%2011%3A19%3A39; st_inirUrl=https%3A%2F%2Fcn.bing.com%2F; st_sn=2; st_psi=20260608170650776-113300300815-6605428830; JSESSIONID=21263EB4A23631E538B1DC68F33D33D1




# huohu
#dongfangcaifu.cookie=websitepoptg_api_time=1780482585894; qgqp_b_id=6cda3bb83477dcc1b0f473d49bca66c1; st_nvi=SSpacE_8M1XrM6Cfm7CJP3e02; nid18=01c55dc01b2e7526ffff0ba54ad506e6; nid18_create_time=1780375043571; gviem=S0rm888IjHpB6mqWvtxBt372c; gviem_create_time=1780375043571; mtp=1; sid=; vtpst=|; fullscreengg=1; fullscreengg2=1; st_si=73795467125110; st_sn=8; st_psi=20260605125619287-113300300815-1132697760; st_asi=delete; p_origin=https%3A%2F%2Fpassport2.eastmoney.com; ct=QfAjuNERJpImdI_TasBsbskNnV-BwgD0ycU5i8iihA2IN3ESDBv0jVP57VU9-z909WHKSuXPtEvgoY3zpJn8mu_bEM7nTSTXnTEGuqfeDP4Q8_Qz1rlweWWL6ycqJ9owC6MKpXvKSjyXwohJrkQFE-xLJtgq09yGOY5p4H2kzYk; ut=FobyicMgeV7nSDOYYA_TdK4IgYmZarMyGE8Kqz_FDk3Q7xmds2cH9A2bMxLBXJJkc59Gx3wBY9GB4SroioJ6zzQIF5xhUQj6rbUUIrn4IYqX_SPKDHfaZEeQnq29BULW-2zlDRvTPZ7RaPCI4hHWxRgxAP6_3xB1FFeOkQAS4OR9CLx8Lg2kN8MlJ7Plf62gLmsDL0a-zeRdJlU3A6YswQohpdEi-fzuZdadoqmj1BWWM-lAsU6uF1Ob4G9ibbmbjmFCQIO07VqxRjqviQH1r4eK3dAMWCvgDN8sPoi5wJQdMUid_VnrP70ZDqBYeJbaiXnnMAiMMdUjyMfsx7gwwmIAAC9xJpDGAfeclFCtWir_LefZbNSGK7JUS0Nz527jrQ_fvLt-pncbHVoOd4lgRbS25iUqBfAknkEpRQoMJkgIWLnadyoy2R5xdxdv7PRDrw3KUT9B_wrLxstj2JKl7zDVHIgRk6Gk9CBLtsFbCDn4gsF8loUCXQ; pi=9283027483348500%3Bt9283027483348500%3B%E8%82%A1%E5%8F%8BA50921282v%3BYjFXdYAfaPTWkznvNgH8eJfwRqHyaAHYN0mylqQ7%2BOfw1bMgEECxgWL3PBcj7vCcfk1q40t0nUOrGqirNqCRQVzkUX0mDsSHmtJ8ln25elklLvzWFPlCslBbfuYUXH%2Bg5zqGz%2FFyVDUh3hq%2BKhIzVlakLgNlKMonOwrh67l78xQ3aCTQ7aI41%2FhDEyI3NqDK7BGIu2%2FC%3B7AVQQbRImjJTsIpHSh39Y%2F%2BzJyQ23L0sDQyGvAyt9cAQbcx4cPDt0OoT5B6pPp0skv6afrb34k7f0aNQm1%2FhgKOrOufTQXXHbmZ6zh9%2Bq%2B1%2F%2ByTVLSiFOgwDglC8w30YzfQotHlSlJ9o8elAJb9SmXL%2BbVEbTQ%3D%3D; uidal=9283027483348500%e8%82%a1%e5%8f%8bA50921282v; wsc_checkuser_ok=1; st_pvi=50252925288931; st_sp=2026-06-02%2012%3A37%3A22; st_inirUrl=https%3A%2F%2Fwww.baidu.com%2Flink



# chrome
#dongfangcaifu.cookie=qgqp_b_id=4377d6888df3e732b83d70462bae5aa3; st_nvi=vGOyypUK-_q6ogqV20r6v2773; nid18=0bcd9d7a85d5e7327284b540d8fb8064; nid18_create_time=1776329780923; gviem=kPYA48ugc7wwaEpwCggWqf8bc; gviem_create_time=1776329780923; mtp=1; vtpst=|; st_si=79970235901550; fullscreengg=1; fullscreengg2=1; p_origin=https%3A%2F%2Fpassport2.eastmoney.com; ct=z_ESiTszPWxKL6m6GGbwBLLVl_LrnsJUgnrv_2fWKuOpfn-QVu9Ki4Nelo0je-X-HjBvQTqIMP6Zdby-rFYHTY2FkUPZMiZsnmonDJojmoIkx1xTVdXD_rI-K7OYu0gvuhM6BWDD1VhXAX7P2sXo9Go-mCOsU9lhiR3GhxSC0jU; ut=FobyicMgeV7jAbDvWsGTbmaSQyp6TmRrM6Oh1dYczXtcaxRnKfZ9eOCvLAUBY7DBASLowJoQHM0s5J2Y50-Awsj3z1gRaYbfs9bSSqvQ9NUo3cEHCKU3r0krn040-0OWOSl2HBR9qICGoI5RXtv_yDawEYPyN5HDovis42DYShKjVRVz1Zg5mrRRdDgcNHoNrdGP8ITSNx_Wjc8sPzx_RGDOTB2CODHMPmx55Fl5pIqWgy6kUQYNVdsD0BcNCSqwfgA34ng8h1tPZB_mFwbG4XaD3Ue4oef-fSBCNPU8qj-Iewe5gRiT9EsgMYhB-QG_XVmem9Hs_iluyAANHNxCZ8VF6f6Op9SD_uHFoJCOE2nnQfMrGxC2q3-4Sjq4u71fSN6GDtFz3bvBDjGXyXOfw9XxQUlS_POGWwa-AOUPao10s0rLBsK7f1S-Dx9WHGl1f54o6lwg742uqey6jnfVKEZ2ldPOpjh6J4d3EpeIdnath0SUruw2RG225oNk4xrMx2LLTIGdq0YxbPnnL7yIPg; pi=9283027483348500%3Bt9283027483348500%3B%E8%82%A1%E5%8F%8BA50921282v%3BFNEzJEzEGWOyh7pZeqL5VZRsBsSo2DncYYPEyjrlOZpuZfoADWrHrc0mAbfWQVBkSD7ztFL06pav0vddq4i88jja2ERL%2F7KinYu9XO8pIvzJf1kP8BccIGx2%2BjjK0Z2bif3jJ2E67hJD9HHdn3U4qjp%2BGB4wHG1QsokeYmSm0rph0RBOyHxM4LQTFlTCd6an25T2YjSX%3BrT2NR7o%2F%2FzQPYZ0Z4Z1xeTS0mDRMDGCj9f2eL9esuk%2FnCNX3UV6FfpGdYhJe3CH9bDFPuBjoImAE8%2Fkr5uuYP3XArPj2mPmrsoQkK4iAzYpUJ3ulZ72cvEIbr3ahE8j1wtn7NaquukHF0CW%2Fy92qWlXWk%2BwvZQ%3D%3D; uidal=9283027483348500%e8%82%a1%e5%8f%8bA50921282v; sid=; wsc_checkuser_ok=1; st_pvi=96748644565460; st_sp=2025-03-06%2016%3A13%3A31; st_inirUrl=https%3A%2F%2Fwww.baidu.com%2Flink; st_sn=5; st_psi=20260608170149816-113300300815-7298710774; st_asi=delete




day.flag = 1


feishu.appId = cli_a9570c9e557b9bd7
feishu.appsecret = 0IwPiyk7sj3mK6saLtvIScsZGbcW6wSd



