spring.web.resources.static-locations= classpath:/static/, classpath:/templates/
server.port=8080
chatgpt.apiKey=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
chatgpt.apiHost=https://api.openai.com/
# key,Use your own key
SECRET_KEY=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
connectTimeout=60000
connectionRequestTimeout=60000
socketTimeout=60000
#
#spring.mail.host=smtp.qq.com
#spring.mail.port=587
#spring.mail.username=1364549020@qq.com
#spring.mail.password=gvpweprmkzlgheca
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#
spring.mail.host=smtp.qq.com
spring.mail.port=587
#spring.mail.port=465
spring.mail.username=3170085380@qq.com
spring.mail.password=rxnwknvhrnkqdfdb
spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.socketFactory.class=jetavax.n.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.starttls.enable=true


spring.datasource.url = jdbc:mysql://localhost:3306/dangfangcaifu?characterEncoding=utf-8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8

spring.datasource.username = root
spring.datasource.password = 123456
spring.datasource.hikari.maximum-pool-size = 15

wx.appId=wxc595fde6ad629391
wx.appSecret=??AppSecret


# ?spring????bean?id, ????forestConfiguration
forest.bean-id=forestConfiguration
# ??HTTP API? ?????okhttp3????????httpclient
forest.backend=okhttp3
# ?????????????500
forest.max-connections=1000
# ???????????????500
forest.max-route-connections=500
# ????????????, ????3000
forest.timeout=3000
# ????????????, ????2000
forest.connect-timeout=3000
# ?????HTTPS???SSL??????SSLv3
#forest.ssl-protocol=SSLv3
# ???????????true??????????????????@LogEnabled
forest.logEnabled=true


dongfangcaifu.cookie=qgqp_b_id=dc483e32c2d8b96bdedb5d061884ce60; st_nvi=Q05vtEKnqLTbIbjENZn5La7ea; mtp=1; ct=bbPIxIRv5aT8OjezQ3qiHHSnED7mVNJHtXg1CIkHth4qoDmN9nJCgFS5jjjEDFpzV7GqEhyBvU0PHAjkV9U56xEGS_puWkfaHeNYxHyWUG153vl0n6dCk4rOtL7Wqk9VlydEIo_EWSOYc2m0e2pwdjy3iZaTlfWlF4cvJDt6rEU; ut=FobyicMgeV6Hb_DbDix6-AtblMI-vv5H7a-yPfrK07aUW4EAvFbvTAcYom93j2KgqfZ_oKmFLdF0m3QtyilXRtw_1i8C3gUeFzlYgfkcCOByFpKmsIZvo6SHEIfJj7r2GbNjMVYOblQm2olWFPemu5DGtW-GEV57PO-EK-kxQsx03hP2KG5iMIIxp7N6cRFPX45MU4-j9NtF6jDc4eZcjtO3967Ls4MWe7BC0WCioQ5FtnvE93lUuOKDR3SDKALT-CRWXde40N3I9tZ5AA740TnhhD1YNPXH; pi=9250355984212214%3Bw9250355984212214%3B%E8%82%A1%E5%8F%8Bhy9Epm%3B4C0yl6lpqDCjqaWdZG20HlSufOgTZZe0pWrbrZ6ravQ%2F%2FobxSEThikNATaKGau8USrgl961UCxpW7JZVcPczDioYFiI7YFOEHhYSUxRMo3J7GwDxNLxi7W3dNCKJdCKE6HyIth5bK7vRGiNSuYcd0sU%2BHImJfaLS2Hr%2B%2B%2FChODPf1i%2F1w2%2Baiaj5SsSc6bZ1hPTiCNCp%3B626TH8AfWTomsJtPww0KtRb%2BcqyT0f9yIi6gsWLuWLMggayqDxhcGazh%2BXREZIMrGFaZPH1xEyOfH2Qsbnazu35jC7HWmc8W6gsDo0nERDBhDOwrC1SsgY1oJJscZ2A%2Fd1zbK5GGtXy%2B4olCj7V7h7yS2Xu8Cg%3D%3D; uidal=9250355984212214%e8%82%a1%e5%8f%8bhy9Epm; sid=151394505; vtpst=|; nid18=0bcd9d7a85d5e7327284b540d8fb8064; nid18_create_time=1776154218768; gviem=At93iLMdLhDE2A0BYhEyxeda4; gviem_create_time=1776154218768; emshistory=%5B%22%E6%B2%AA%E8%82%A1%E9%80%9A%22%5D; quote_lt=1; st_si=82456641995735; fullscreengg=1; fullscreengg2=1; has_jump_to_web=1; websitepoptg_api_time=1779070222638; st_pvi=82959104877326; st_sp=2025-03-04%2011%3A19%3A39; st_inirUrl=https%3A%2F%2Fcn.bing.com%2F; st_sn=246; st_psi=20260518114254851-113300300815-1594943238; st_asi=delete; wsc_checkuser_ok=1
##dongfangcaifu.cookie=qgqp_b_id=4377d6888df3e732b83d70462bae5aa3; st_nvi=vGOyypUK-_q6ogqV20r6v2773; nid18=0bcd9d7a85d5e7327284b540d8fb8064; nid18_create_time=1776329780923; gviem=kPYA48ugc7wwaEpwCggWqf8bc; gviem_create_time=1776329780923; websitepoptg_api_time=1779088063183; st_si=75224817008792; st_asi=delete; wsc_checkuser_ok=1; fullscreengg=1; fullscreengg2=1; p_origin=https%3A%2F%2Fpassport2.eastmoney.com; mtp=1; ct=bSYXPaK0huT0hMl4Zy58rQ2orZKCzF-4s2IW1HbQWkmk7JL8YLBDMuByYFwD2q7DNvF6xPG3YJnIR6LIv4YKLkCEezCg2do-OxMWX76OaNY41NAq6eh1D1FHgA8Y-cteRsa8S4ADimzH_mZA2xMiBgjDmMmtES8QRm3GmNAKKF4; ut=FobyicMgeV7n9HbgC1xlGDIcOuAhk66jCuqDqWtH9ALhd_0tVtlGV6SYIC4Y3I1m8J__NoguCmaQSJYUqmd9R6Akz046HOEJzI9fLCJ33ks704cfdzTE5GFHiYcVUa-xuiAq5r2oQKxcj8fslMuVLyc1mGFZheTU6xL2ulriI6e5n7DesFNHZ75rBNv3WAUI8aKthEWxaNSvazYvOnrYhyNb-Nna5sWG-hjS4ABE2xfavJOwasDOAbPQWF7f3zXmEqHJ2VqbLZ2_RP5b7I4HLx6xacDDBOMIfKPKLgC-tQMsQYTyBTYjc7_OZ7OlM-rltocC9oEarXXbxjc0T-Wys7QXOwi29AsRa6NRsKYgGg8KUJ6wXUjTlQVV4OYehpqhZUCCUj5rqIaHdj5imrwuxkvZSFbuo-S8qEt0_DuyfxkmwPXXalxdr4JUBWkrHhSGLhYlDfwhNaBzfRlLT-RMnpTg3J19lg0GcBd5Hb_BekXMX3gXwXWZagEG1MY8P3tdEiK7aF0ZR4_jQLcTwdSVcg; pi=9250355984212214%3Bw9250355984212214%3B%E8%82%A1%E5%8F%8Bhy9Epm%3BsVr5PS%2ByrSHzMSiHgvW0Dt0THlAk4QoN4DiOrHJqaSRcBbl3HcYA0pU0Xj9errbrlPMcybAt3ZDfxpPQeSYhV1xiTfZcSSE0%2Fhnxm9618jFdI%2BNNwGSosKSjfwr5jUgu%2Ff%2BG4nPkiUphxgIencxnjWVf3kbF2fXc1kq4rz%2FxcmI3wiY19DC43lsIlhNfpTFLxn%2BUEHwT%3B9BHV9BuC5a0YqJGwWfaII8AfAgJDVowg9HJSFFTDDhfYynSWshYkERKxpWFjt%2BNSKOHJvUgMKAbO8xwThX2%2Fmn9u%2B19jjcA1hyFnKAi%2F6pdWo5M1WPtm1kVn19MjYIh%2F2CXgzD1tXyhcTeAy5tCcJ9lAFrleUg%3D%3D; uidal=9250355984212214%e8%82%a1%e5%8f%8bhy9Epm; sid=151394505; vtpst=|; st_pvi=96748644565460; st_sp=2025-03-06%2016%3A13%3A31; st_inirUrl=https%3A%2F%2Fwww.baidu.com%2Flink; st_sn=44; st_psi=20260518165832958-113200301321-2900976092



day.flag = 1


feishu.appId = cli_a9570c9e557b9bd7
feishu.appsecret = 0IwPiyk7sj3mK6saLtvIScsZGbcW6wSd



