spring.web.resources.static-locations= classpath:/static/, classpath:/templates/
server.port=8080
chatgpt.apiKey=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
chatgpt.apiHost=https://api.openai.com/
# key,Use your own key
SECRET_KEY=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
connectTimeout=60000
connectionRequestTimeout=60000
socketTimeout=60000
#
#spring.mail.host=smtp.qq.com
#spring.mail.port=587
#spring.mail.username=1364549020@qq.com
#spring.mail.password=gvpweprmkzlgheca
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#
spring.mail.host=smtp.qq.com
spring.mail.port=587
#spring.mail.port=465
spring.mail.username=3170085380@qq.com
spring.mail.password=rxnwknvhrnkqdfdb
spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.socketFactory.class=jetavax.n.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.starttls.enable=true


spring.datasource.url = jdbc:mysql://localhost:3306/dangfangcaifu?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8

spring.datasource.username = root
spring.datasource.password = 123456
spring.datasource.hikari.maximum-pool-size = 15

wx.appId=wxc595fde6ad629391
wx.appSecret=??AppSecret


# ?spring????bean?id, ????forestConfiguration
forest.bean-id=forestConfiguration
# ??HTTP API? ?????okhttp3????????httpclient
forest.backend=okhttp3
# ?????????????500
forest.max-connections=1000
# ???????????????500
forest.max-route-connections=500
# ????????????, ????3000
forest.timeout=3000
# ????????????, ????2000
forest.connect-timeout=3000
# ?????HTTPS???SSL??????SSLv3
#forest.ssl-protocol=SSLv3
# ???????????true??????????????????@LogEnabled
forest.logEnabled=true


